var annotated_dup =
[
    [ "Api", "namespaceApi.html", [
      [ "Controllers", "namespaceApi_1_1Controllers.html", [
        [ "AuthController", "classApi_1_1Controllers_1_1AuthController.html", "classApi_1_1Controllers_1_1AuthController" ],
        [ "DriverController", "classApi_1_1Controllers_1_1DriverController.html", "classApi_1_1Controllers_1_1DriverController" ],
        [ "GPSController", "classApi_1_1Controllers_1_1GPSController.html", "classApi_1_1Controllers_1_1GPSController" ],
        [ "NotificationsController", "classApi_1_1Controllers_1_1NotificationsController.html", "classApi_1_1Controllers_1_1NotificationsController" ],
        [ "PingController", "classApi_1_1Controllers_1_1PingController.html", "classApi_1_1Controllers_1_1PingController" ],
        [ "ReportsController", "classApi_1_1Controllers_1_1ReportsController.html", null ],
        [ "RiderController", "classApi_1_1Controllers_1_1RiderController.html", "classApi_1_1Controllers_1_1RiderController" ],
        [ "ScheduleController", "classApi_1_1Controllers_1_1ScheduleController.html", "classApi_1_1Controllers_1_1ScheduleController" ],
        [ "TransportationTypesController", "classApi_1_1Controllers_1_1TransportationTypesController.html", "classApi_1_1Controllers_1_1TransportationTypesController" ],
        [ "TripsController", "classApi_1_1Controllers_1_1TripsController.html", "classApi_1_1Controllers_1_1TripsController" ],
        [ "TripStatusHistoryController", "classApi_1_1Controllers_1_1TripStatusHistoryController.html", "classApi_1_1Controllers_1_1TripStatusHistoryController" ],
        [ "VehicleController", "classApi_1_1Controllers_1_1VehicleController.html", "classApi_1_1Controllers_1_1VehicleController" ]
      ] ],
      [ "Data", "namespaceApi_1_1Data.html", [
        [ "AppDbContext", "classApi_1_1Data_1_1AppDbContext.html", "classApi_1_1Data_1_1AppDbContext" ]
      ] ],
      [ "DTOs", "namespaceApi_1_1DTOs.html", [
        [ "ActiveDriversPositionsResponse", "classApi_1_1DTOs_1_1ActiveDriversPositionsResponse.html", "classApi_1_1DTOs_1_1ActiveDriversPositionsResponse" ],
        [ "AssignTripRequest", "classApi_1_1DTOs_1_1AssignTripRequest.html", "classApi_1_1DTOs_1_1AssignTripRequest" ],
        [ "AuthResponse", "classApi_1_1DTOs_1_1AuthResponse.html", "classApi_1_1DTOs_1_1AuthResponse" ],
        [ "CancelTripRequest", "classApi_1_1DTOs_1_1CancelTripRequest.html", "classApi_1_1DTOs_1_1CancelTripRequest" ],
        [ "CompleteTripRequest", "classApi_1_1DTOs_1_1CompleteTripRequest.html", "classApi_1_1DTOs_1_1CompleteTripRequest" ],
        [ "CreateDriverRequest", "classApi_1_1DTOs_1_1CreateDriverRequest.html", "classApi_1_1DTOs_1_1CreateDriverRequest" ],
        [ "CreateGPSBreadcrumbRequest", "classApi_1_1DTOs_1_1CreateGPSBreadcrumbRequest.html", "classApi_1_1DTOs_1_1CreateGPSBreadcrumbRequest" ],
        [ "CreateRiderRequest", "classApi_1_1DTOs_1_1CreateRiderRequest.html", "classApi_1_1DTOs_1_1CreateRiderRequest" ],
        [ "CreateSpecialScheduleRequest", "classApi_1_1DTOs_1_1CreateSpecialScheduleRequest.html", "classApi_1_1DTOs_1_1CreateSpecialScheduleRequest" ],
        [ "CreateTransportationTypeRequest", "classApi_1_1DTOs_1_1CreateTransportationTypeRequest.html", "classApi_1_1DTOs_1_1CreateTransportationTypeRequest" ],
        [ "CreateTripRequest", "classApi_1_1DTOs_1_1CreateTripRequest.html", "classApi_1_1DTOs_1_1CreateTripRequest" ],
        [ "CreateVehicleRequest", "classApi_1_1DTOs_1_1CreateVehicleRequest.html", "classApi_1_1DTOs_1_1CreateVehicleRequest" ],
        [ "DenyTripRequest", "classApi_1_1DTOs_1_1DenyTripRequest.html", "classApi_1_1DTOs_1_1DenyTripRequest" ],
        [ "DriverLatestPositionResponse", "classApi_1_1DTOs_1_1DriverLatestPositionResponse.html", "classApi_1_1DTOs_1_1DriverLatestPositionResponse" ],
        [ "DriverResponse", "classApi_1_1DTOs_1_1DriverResponse.html", "classApi_1_1DTOs_1_1DriverResponse" ],
        [ "GPSBreadcrumbResponse", "classApi_1_1DTOs_1_1GPSBreadcrumbResponse.html", "classApi_1_1DTOs_1_1GPSBreadcrumbResponse" ],
        [ "LoginRequest", "classApi_1_1DTOs_1_1LoginRequest.html", "classApi_1_1DTOs_1_1LoginRequest" ],
        [ "MarkReadRequest", "classApi_1_1DTOs_1_1MarkReadRequest.html", "classApi_1_1DTOs_1_1MarkReadRequest" ],
        [ "NotificationResponse", "classApi_1_1DTOs_1_1NotificationResponse.html", "classApi_1_1DTOs_1_1NotificationResponse" ],
        [ "OperatingHoursResponse", "classApi_1_1DTOs_1_1OperatingHoursResponse.html", "classApi_1_1DTOs_1_1OperatingHoursResponse" ],
        [ "PagedNotificationResponse", "classApi_1_1DTOs_1_1PagedNotificationResponse.html", "classApi_1_1DTOs_1_1PagedNotificationResponse" ],
        [ "RealtimeLocationUpdate", "classApi_1_1DTOs_1_1RealtimeLocationUpdate.html", "classApi_1_1DTOs_1_1RealtimeLocationUpdate" ],
        [ "RegisterRequest", "classApi_1_1DTOs_1_1RegisterRequest.html", "classApi_1_1DTOs_1_1RegisterRequest" ],
        [ "RiderResponse", "classApi_1_1DTOs_1_1RiderResponse.html", "classApi_1_1DTOs_1_1RiderResponse" ],
        [ "SpecialScheduleResponse", "classApi_1_1DTOs_1_1SpecialScheduleResponse.html", "classApi_1_1DTOs_1_1SpecialScheduleResponse" ],
        [ "TransportationTypeResponse", "classApi_1_1DTOs_1_1TransportationTypeResponse.html", "classApi_1_1DTOs_1_1TransportationTypeResponse" ],
        [ "TripQueryParams", "classApi_1_1DTOs_1_1TripQueryParams.html", "classApi_1_1DTOs_1_1TripQueryParams" ],
        [ "TripRequest", "classApi_1_1DTOs_1_1TripRequest.html", "classApi_1_1DTOs_1_1TripRequest" ],
        [ "TripResponse", "classApi_1_1DTOs_1_1TripResponse.html", "classApi_1_1DTOs_1_1TripResponse" ],
        [ "UpdateDriverRequest", "classApi_1_1DTOs_1_1UpdateDriverRequest.html", "classApi_1_1DTOs_1_1UpdateDriverRequest" ],
        [ "UpdateOperatingHoursRequest", "classApi_1_1DTOs_1_1UpdateOperatingHoursRequest.html", "classApi_1_1DTOs_1_1UpdateOperatingHoursRequest" ],
        [ "UpdateRiderRequest", "classApi_1_1DTOs_1_1UpdateRiderRequest.html", "classApi_1_1DTOs_1_1UpdateRiderRequest" ],
        [ "UpdateSpecialDatesRequest", "classApi_1_1DTOs_1_1UpdateSpecialDatesRequest.html", "classApi_1_1DTOs_1_1UpdateSpecialDatesRequest" ],
        [ "UpdateSpecialSchedulesRequest", "classApi_1_1DTOs_1_1UpdateSpecialSchedulesRequest.html", null ],
        [ "UpdateTransportationTypeRequest", "classApi_1_1DTOs_1_1UpdateTransportationTypeRequest.html", "classApi_1_1DTOs_1_1UpdateTransportationTypeRequest" ],
        [ "UpdateTripRequest", "classApi_1_1DTOs_1_1UpdateTripRequest.html", "classApi_1_1DTOs_1_1UpdateTripRequest" ],
        [ "UpdateVehicleRequest", "classApi_1_1DTOs_1_1UpdateVehicleRequest.html", "classApi_1_1DTOs_1_1UpdateVehicleRequest" ],
        [ "VehicleResponse", "classApi_1_1DTOs_1_1VehicleResponse.html", "classApi_1_1DTOs_1_1VehicleResponse" ]
      ] ],
      [ "Hubs", "namespaceApi_1_1Hubs.html", [
        [ "GpsHub", "classApi_1_1Hubs_1_1GpsHub.html", "classApi_1_1Hubs_1_1GpsHub" ]
      ] ],
      [ "Migrations", "namespaceApi_1_1Migrations.html", [
        [ "AddGPSAndNotifications", "classApi_1_1Migrations_1_1AddGPSAndNotifications.html", "classApi_1_1Migrations_1_1AddGPSAndNotifications" ],
        [ "AddNewTables", "classApi_1_1Migrations_1_1AddNewTables.html", "classApi_1_1Migrations_1_1AddNewTables" ],
        [ "AppDbContextModelSnapshot", "classApi_1_1Migrations_1_1AppDbContextModelSnapshot.html", "classApi_1_1Migrations_1_1AppDbContextModelSnapshot" ],
        [ "InitialCreate", "classApi_1_1Migrations_1_1InitialCreate.html", "classApi_1_1Migrations_1_1InitialCreate" ]
      ] ],
      [ "Models", "namespaceApi_1_1Models.html", [
        [ "Driver", "classApi_1_1Models_1_1Driver.html", "classApi_1_1Models_1_1Driver" ],
        [ "GPS_Track_Point", "classApi_1_1Models_1_1GPS__Track__Point.html", "classApi_1_1Models_1_1GPS__Track__Point" ],
        [ "Hours_of_Operation", "classApi_1_1Models_1_1Hours__of__Operation.html", "classApi_1_1Models_1_1Hours__of__Operation" ],
        [ "Notification", "classApi_1_1Models_1_1Notification.html", "classApi_1_1Models_1_1Notification" ],
        [ "RecurrenceRule", "classApi_1_1Models_1_1RecurrenceRule.html", "classApi_1_1Models_1_1RecurrenceRule" ],
        [ "Rider", "classApi_1_1Models_1_1Rider.html", "classApi_1_1Models_1_1Rider" ],
        [ "SpecialDate", "classApi_1_1Models_1_1SpecialDate.html", "classApi_1_1Models_1_1SpecialDate" ],
        [ "TransportationType", "classApi_1_1Models_1_1TransportationType.html", "classApi_1_1Models_1_1TransportationType" ],
        [ "Trip", "classApi_1_1Models_1_1Trip.html", "classApi_1_1Models_1_1Trip" ],
        [ "TripStatusHistory", "classApi_1_1Models_1_1TripStatusHistory.html", "classApi_1_1Models_1_1TripStatusHistory" ],
        [ "User", "classApi_1_1Models_1_1User.html", "classApi_1_1Models_1_1User" ],
        [ "Vehicle", "classApi_1_1Models_1_1Vehicle.html", "classApi_1_1Models_1_1Vehicle" ]
      ] ],
      [ "Services", "namespaceApi_1_1Services.html", [
        [ "AuthService", "classApi_1_1Services_1_1AuthService.html", "classApi_1_1Services_1_1AuthService" ],
        [ "DriverService", "classApi_1_1Services_1_1DriverService.html", "classApi_1_1Services_1_1DriverService" ],
        [ "GPSService", "classApi_1_1Services_1_1GPSService.html", "classApi_1_1Services_1_1GPSService" ],
        [ "NotificationDispatcher", "classApi_1_1Services_1_1NotificationDispatcher.html", "classApi_1_1Services_1_1NotificationDispatcher" ],
        [ "NotificationService", "classApi_1_1Services_1_1NotificationService.html", "classApi_1_1Services_1_1NotificationService" ],
        [ "RiderService", "classApi_1_1Services_1_1RiderService.html", "classApi_1_1Services_1_1RiderService" ],
        [ "ScheduleService", "classApi_1_1Services_1_1ScheduleService.html", "classApi_1_1Services_1_1ScheduleService" ],
        [ "TransportationTypeService", "classApi_1_1Services_1_1TransportationTypeService.html", "classApi_1_1Services_1_1TransportationTypeService" ],
        [ "TripService", "classApi_1_1Services_1_1TripService.html", "classApi_1_1Services_1_1TripService" ],
        [ "VehicleService", "classApi_1_1Services_1_1VehicleService.html", "classApi_1_1Services_1_1VehicleService" ]
      ] ]
    ] ],
    [ "docstring", "namespacedocstring.html", [
      [ "PyClass", "classdocstring_1_1PyClass.html", "classdocstring_1_1PyClass" ]
    ] ],
    [ "pyexample", "namespacepyexample.html", [
      [ "PyClass", "classpyexample_1_1PyClass.html", "classpyexample_1_1PyClass" ]
    ] ],
    [ "A", "classA.html", "classA" ],
    [ "Afterdoc_Test", "classAfterdoc__Test.html", "classAfterdoc__Test" ],
    [ "Autolink_Test", "classAutolink__Test.html", "classAutolink__Test" ],
    [ "B", "classB.html", "classB" ],
    [ "C", "classC.html", "classC" ],
    [ "C1", "classC1.html", null ],
    [ "C2", "classC2.html", null ],
    [ "C3", "classC3.html", null ],
    [ "C4", "classC4.html", null ],
    [ "C5", "classC5.html", null ],
    [ "Calender", "classCalender.html", "classCalender" ],
    [ "Car", "structCar.html", "structCar" ],
    [ "CoordStruct", "structCoordStruct.html", "structCoordStruct" ],
    [ "D", "classD.html", "classD" ],
    [ "E", "classE.html", null ],
    [ "Enum_Test", "classEnum__Test.html", "classEnum__Test" ],
    [ "Example_Test", "classExample__Test.html", "classExample__Test" ],
    [ "Fn_Test", "classFn__Test.html", "classFn__Test" ],
    [ "Include_Test", "classInclude__Test.html", "classInclude__Test" ],
    [ "Javadoc_Test", "classJavadoc__Test.html", "classJavadoc__Test" ],
    [ "Memgrp_Test", "classMemgrp__Test.html", "classMemgrp__Test" ],
    [ "mux_using_with", "classmux__using__with.html", "classmux__using__with" ],
    [ "Object", "structObject.html", null ],
    [ "Overload_Test", "classOverload__Test.html", "classOverload__Test" ],
    [ "Par_Test", "classPar__Test.html", null ],
    [ "QTstyle_Test", "classQTstyle__Test.html", "classQTstyle__Test" ],
    [ "SomeNiceClass", "classSomeNiceClass.html", null ],
    [ "String", "classString.html", "classString" ],
    [ "Tag", "classTag.html", "classTag" ],
    [ "Test", "classTest.html", "classTest" ],
    [ "Test< T * >", "classTest_3_01T_01_5_01_4.html", "classTest_3_01T_01_5_01_4" ],
    [ "Test< void *, 200 >", "classTest_3_01void_01_5_00_01200_01_4.html", "classTest_3_01void_01_5_00_01200_01_4" ],
    [ "Truck", "structTruck.html", "structTruck" ],
    [ "Vehicle", "structVehicle.html", "structVehicle" ]
];