var searchData=
[
  ['calender_0',['Calender',['../class_calender.html',1,'']]],
  ['cancel_1',['POST /api/trips/{id}/cancel',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['canceltriprequest_2',['CancelTripRequest',['../class_api_1_1_d_t_os_1_1_cancel_trip_request.html',1,'Api::DTOs']]],
  ['changes_20april_202_202026_3',['Recent Changes (April 2, 2026)',['../md__r_e_a_d_m_e.html#autotoc_md99',1,'']]],
  ['check_4',['Health Check',['../md__r_e_a_d_m_e.html#autotoc_md108',1,'']]],
  ['check_20the_20audit_20trail_5',['Step 14: Check the Audit Trail',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md83',1,'']]],
  ['closedflag_6',['closedFlag',['../class_api_1_1_models_1_1_special_date.html#a62a67991cbac1a74cabcd823756d4233',1,'Api::Models::SpecialDate']]],
  ['compiler_7',['React Compiler',['../dir_922c588100a187620fdc1533bc178f73.html#autotoc_md1',1,'']]],
  ['complete_8',['POST /api/trips/{id}/complete',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['complete_20the_20trip_9',['Step 13: Complete the Trip',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md82',1,'']]],
  ['completetriprequest_10',['CompleteTripRequest',['../class_api_1_1_d_t_os_1_1_complete_trip_request.html',1,'Api::DTOs']]],
  ['configuration_11',['Expanding the ESLint configuration',['../dir_922c588100a187620fdc1533bc178f73.html#autotoc_md2',1,'']]],
  ['configuration_20updates_12',['Configuration Updates',['../md__r_e_a_d_m_e.html#autotoc_md103',1,'']]],
  ['create_20a_20driver_13',['Step 6: Create a Driver',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md75',1,'']]],
  ['create_20a_20rider_14',['Step 5: Create a Rider',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md74',1,'']]],
  ['create_20a_20transportation_20type_15',['Step 4: Create a Transportation Type',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md73',1,'']]],
  ['create_20a_20trip_16',['Step 8: Create a Trip',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md77',1,'']]],
  ['create_20a_20vehicle_17',['Step 7: Create a Vehicle',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md76',1,'']]],
  ['createdriverrequest_18',['CreateDriverRequest',['../class_api_1_1_d_t_os_1_1_create_driver_request.html',1,'Api::DTOs']]],
  ['creategpsbreadcrumbrequest_19',['CreateGPSBreadcrumbRequest',['../class_api_1_1_d_t_os_1_1_create_g_p_s_breadcrumb_request.html',1,'Api::DTOs']]],
  ['createriderrequest_20',['CreateRiderRequest',['../class_api_1_1_d_t_os_1_1_create_rider_request.html',1,'Api::DTOs']]],
  ['createspecialschedulerequest_21',['CreateSpecialScheduleRequest',['../class_api_1_1_d_t_os_1_1_create_special_schedule_request.html',1,'Api::DTOs']]],
  ['createtransportationtyperequest_22',['CreateTransportationTypeRequest',['../class_api_1_1_d_t_os_1_1_create_transportation_type_request.html',1,'Api::DTOs']]],
  ['createtriprequest_23',['CreateTripRequest',['../class_api_1_1_d_t_os_1_1_create_trip_request.html',1,'Api::DTOs']]],
  ['createtripstatushistoryrequest_24',['CreateTripStatusHistoryRequest',['../class_api_1_1_controllers_1_1_trip_status_history_controller_1_1_create_trip_status_history_request.html',1,'Api::Controllers::TripStatusHistoryController']]],
  ['createvehiclerequest_25',['CreateVehicleRequest',['../class_api_1_1_d_t_os_1_1_create_vehicle_request.html',1,'Api::DTOs']]],
  ['crud_20endpoints_26',['CRUD Endpoints',['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md65',1,'']]],
  ['current_20submission_20transportation_20management_20system_20april_202_202026_27',['Current Submission - Transportation Management System (April 2, 2026)',['../md__r_e_a_d_m_e.html#autotoc_md93',1,'']]]
];
