var searchData=
[
  ['a_20driver_0',['Step 6: Create a Driver',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md75',1,'']]],
  ['a_20rider_1',['Step 5: Create a Rider',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md74',1,'']]],
  ['a_20transportation_20type_2',['Step 4: Create a Transportation Type',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md73',1,'']]],
  ['a_20trip_3',['Step 8: Create a Trip',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md77',1,'']]],
  ['a_20user_4',['Step 1: Register a User',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md70',1,'']]],
  ['a_20vehicle_5',['Step 7: Create a Vehicle',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md76',1,'']]],
  ['actions_6',['Trip Status Actions',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['activedriverspositionsresponse_7',['ActiveDriversPositionsResponse',['../class_api_1_1_d_t_os_1_1_active_drivers_positions_response.html',1,'Api::DTOs']]],
  ['added_8',['Added',['../md__r_e_a_d_m_e.html#autotoc_md101',1,'API Endpoints Added'],['../md__r_e_a_d_m_e.html#autotoc_md104',1,'Documentation Added'],['../md__r_e_a_d_m_e.html#autotoc_md102',1,'DTOs Added']]],
  ['added_20updated_9',['Models Added/Updated',['../md__r_e_a_d_m_e.html#autotoc_md100',1,'']]],
  ['addnewtables_10',['AddNewTables',['../class_api_1_1_migrations_1_1_add_new_tables.html',1,'Api::Migrations']]],
  ['admin_11',['Admin',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md71',1,'Step 2: Promote to Admin'],['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md72',1,'Step 3: Login as Admin']]],
  ['admin_12',['POST /api/auth/register-admin',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md10',1,'']]],
  ['and_20vehicle_13',['Step 10: Assign Driver and Vehicle',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md79',1,'']]],
  ['api_14',['How to Test the Transportation Types API',['../md__r_e_a_d_m_e.html#autotoc_md109',1,'']]],
  ['api_15',['Api',['../namespace_api.html',1,'']]],
  ['api_20auth_20login_16',['POST /api/auth/login',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md9',1,'']]],
  ['api_20auth_20register_17',['POST /api/auth/register',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md8',1,'']]],
  ['api_20auth_20register_20admin_18',['POST /api/auth/register-admin',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md10',1,'']]],
  ['api_20auth_20register_20driver_19',['POST /api/auth/register-driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md11',1,'']]],
  ['api_20documentation_20',['API Documentation',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html',1,'']]],
  ['api_20driver_21',['api driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md21',1,'GET /api/driver'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md23',1,'POST /api/driver']]],
  ['api_20driver_20id_22',['api driver id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md25',1,'DELETE /api/driver/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md22',1,'GET /api/driver/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md24',1,'PUT /api/driver/{id}']]],
  ['api_20endpoints_20added_23',['API Endpoints Added',['../md__r_e_a_d_m_e.html#autotoc_md101',1,'']]],
  ['api_20endpoints_20summary_24',['API Endpoints Summary',['../md__r_e_a_d_m_e.html#autotoc_md105',1,'']]],
  ['api_20new_20fully_20implemented_25',['✅ Transportation Types API (NEW - Fully Implemented)',['../md__r_e_a_d_m_e.html#autotoc_md95',1,'']]],
  ['api_20rider_26',['api rider',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md14',1,'GET /api/rider'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md16',1,'POST /api/rider']]],
  ['api_20rider_20id_27',['api rider id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md18',1,'DELETE /api/rider/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md15',1,'GET /api/rider/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md17',1,'PUT /api/rider/{id}']]],
  ['api_20transportationtypes_28',['api transportationtypes',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md35',1,'GET /api/transportationtypes'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md37',1,'POST /api/transportationtypes']]],
  ['api_20transportationtypes_20id_29',['api transportationtypes id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md39',1,'DELETE /api/transportationtypes/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md36',1,'GET /api/transportationtypes/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md38',1,'PUT /api/transportationtypes/{id}']]],
  ['api_20trips_30',['api trips',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md42',1,'GET /api/trips'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'POST /api/trips']]],
  ['api_20trips_20id_31',['api trips id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md46',1,'DELETE /api/trips/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md43',1,'GET /api/trips/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md45',1,'PUT /api/trips/{id}']]],
  ['api_20trips_20id_20approve_32',['POST /api/trips/{id}/approve',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['api_20trips_20id_20assign_33',['POST /api/trips/{id}/assign',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['api_20trips_20id_20cancel_34',['POST /api/trips/{id}/cancel',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['api_20trips_20id_20complete_35',['POST /api/trips/{id}/complete',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['api_20trips_20id_20deny_36',['POST /api/trips/{id}/deny',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['api_20trips_20id_20noshow_37',['POST /api/trips/{id}/noshow',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['api_20trips_20id_20start_38',['POST /api/trips/{id}/start',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md52',1,'']]],
  ['api_20tripstatushistory_20trip_20tripid_39',['GET /api/tripstatushistory/trip/{tripId}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md58',1,'']]],
  ['api_20vehicle_40',['api vehicle',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md28',1,'GET /api/vehicle'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md30',1,'POST /api/vehicle']]],
  ['api_20vehicle_20id_41',['api vehicle id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md32',1,'DELETE /api/vehicle/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md29',1,'GET /api/vehicle/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md31',1,'PUT /api/vehicle/{id}']]],
  ['api_3a_3acontrollers_42',['Controllers',['../namespace_api_1_1_controllers.html',1,'Api']]],
  ['api_3a_3adata_43',['Data',['../namespace_api_1_1_data.html',1,'Api']]],
  ['api_3a_3adtos_44',['DTOs',['../namespace_api_1_1_d_t_os.html',1,'Api']]],
  ['api_3a_3ahubs_45',['Hubs',['../namespace_api_1_1_hubs.html',1,'Api']]],
  ['api_3a_3amigrations_46',['Migrations',['../namespace_api_1_1_migrations.html',1,'Api']]],
  ['api_3a_3amodels_47',['Models',['../namespace_api_1_1_models.html',1,'Api']]],
  ['api_3a_3aservices_48',['Services',['../namespace_api_1_1_services.html',1,'Api']]],
  ['appdbcontext_49',['AppDbContext',['../class_api_1_1_data_1_1_app_db_context.html',1,'Api::Data']]],
  ['appdbcontextmodelsnapshot_50',['AppDbContextModelSnapshot',['../class_api_1_1_migrations_1_1_app_db_context_model_snapshot.html',1,'Api::Migrations']]],
  ['application_51',['application',['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md60',1,'What is this application?'],['../md__r_e_a_d_m_e.html#autotoc_md87',1,'What is this application?']]],
  ['approve_52',['POST /api/trips/{id}/approve',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['approve_20the_20trip_53',['Step 9: Approve the Trip',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md78',1,'']]],
  ['april_202_202026_54',['April 2 2026',['../md__r_e_a_d_m_e.html#autotoc_md93',1,'Current Submission - Transportation Management System (April 2, 2026)'],['../md__r_e_a_d_m_e.html#autotoc_md99',1,'Recent Changes (April 2, 2026)']]],
  ['as_20admin_55',['Step 3: Login as Admin',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md72',1,'']]],
  ['as_20driver_56',['Step 11: Login as Driver',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md80',1,'']]],
  ['assign_57',['POST /api/trips/{id}/assign',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['assign_20driver_20and_20vehicle_58',['Step 10: Assign Driver and Vehicle',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md79',1,'']]],
  ['assigntriprequest_59',['AssignTripRequest',['../class_api_1_1_d_t_os_1_1_assign_trip_request.html',1,'Api::DTOs']]],
  ['audit_20trail_60',['Step 14: Check the Audit Trail',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md83',1,'']]],
  ['auth_20endpoints_61',['Auth Endpoints',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md7',1,'']]],
  ['auth_20login_62',['POST /api/auth/login',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md9',1,'']]],
  ['auth_20register_63',['POST /api/auth/register',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md8',1,'']]],
  ['auth_20register_20admin_64',['POST /api/auth/register-admin',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md10',1,'']]],
  ['auth_20register_20driver_65',['POST /api/auth/register-driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md11',1,'']]],
  ['authcontroller_66',['AuthController',['../class_api_1_1_controllers_1_1_auth_controller.html',1,'Api::Controllers']]],
  ['authentication_67',['Authentication',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md5',1,'Authentication'],['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md64',1,'Authentication']]],
  ['authentication_20authorization_20system_68',['✅ Authentication &amp;amp; Authorization System',['../md__r_e_a_d_m_e.html#autotoc_md94',1,'']]],
  ['authentication_20endpoints_69',['Authentication Endpoints',['../md__r_e_a_d_m_e.html#autotoc_md106',1,'']]],
  ['authorization_20system_70',['✅ Authentication &amp;amp; Authorization System',['../md__r_e_a_d_m_e.html#autotoc_md94',1,'']]],
  ['authresponse_71',['AuthResponse',['../class_api_1_1_d_t_os_1_1_auth_response.html',1,'Api::DTOs']]],
  ['authservice_72',['AuthService',['../class_api_1_1_services_1_1_auth_service.html',1,'Api::Services']]]
];
