var searchData=
[
  ['pagednotificationresponse_0',['PagedNotificationResponse',['../class_api_1_1_d_t_os_1_1_paged_notification_response.html',1,'Api::DTOs']]],
  ['pickup_1',['Pickup',['../md__r_e_a_d_m_e.html',1,'Group-9-QLI-Pickup'],['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md59',1,'Group-9-QLI-Pickup']]],
  ['pingcontroller_2',['PingController',['../class_api_1_1_controllers_1_1_ping_controller.html',1,'Api::Controllers']]],
  ['planned_3',['🔄 GPS Tracking (Planned)',['../md__r_e_a_d_m_e.html#autotoc_md98',1,'']]],
  ['post_20api_20auth_20login_4',['POST /api/auth/login',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md9',1,'']]],
  ['post_20api_20auth_20register_5',['POST /api/auth/register',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md8',1,'']]],
  ['post_20api_20auth_20register_20admin_6',['POST /api/auth/register-admin',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md10',1,'']]],
  ['post_20api_20auth_20register_20driver_7',['POST /api/auth/register-driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md11',1,'']]],
  ['post_20api_20driver_8',['POST /api/driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md23',1,'']]],
  ['post_20api_20rider_9',['POST /api/rider',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md16',1,'']]],
  ['post_20api_20transportationtypes_10',['POST /api/transportationtypes',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md37',1,'']]],
  ['post_20api_20trips_11',['POST /api/trips',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['post_20api_20trips_20id_20approve_12',['POST /api/trips/{id}/approve',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['post_20api_20trips_20id_20assign_13',['POST /api/trips/{id}/assign',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['post_20api_20trips_20id_20cancel_14',['POST /api/trips/{id}/cancel',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['post_20api_20trips_20id_20complete_15',['POST /api/trips/{id}/complete',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['post_20api_20trips_20id_20deny_16',['POST /api/trips/{id}/deny',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['post_20api_20trips_20id_20noshow_17',['POST /api/trips/{id}/noshow',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['post_20api_20trips_20id_20start_18',['POST /api/trips/{id}/start',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md52',1,'']]],
  ['post_20api_20vehicle_19',['POST /api/vehicle',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md30',1,'']]],
  ['prerequisites_20',['Prerequisites',['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md61',1,'']]],
  ['production_20mode_21',['Production Mode',['../md__r_e_a_d_m_e.html#autotoc_md91',1,'']]],
  ['promote_20to_20admin_22',['Step 2: Promote to Admin',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md71',1,'']]],
  ['put_20api_20driver_20id_23',['PUT /api/driver/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md24',1,'']]],
  ['put_20api_20rider_20id_24',['PUT /api/rider/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md17',1,'']]],
  ['put_20api_20transportationtypes_20id_25',['PUT /api/transportationtypes/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md38',1,'']]],
  ['put_20api_20trips_20id_26',['PUT /api/trips/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['put_20api_20vehicle_20id_27',['PUT /api/vehicle/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md31',1,'']]]
];
