var searchData=
[
  ['test_20the_20transportation_20types_20api_0',['How to Test the Transportation Types API',['../md__r_e_a_d_m_e.html#autotoc_md109',1,'']]],
  ['testing_20guide_1',['Testing Guide',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html',1,'']]],
  ['testing_20invalid_20transitions_2',['Testing Invalid Transitions',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md84',1,'']]],
  ['the_20audit_20trail_3',['Step 14: Check the Audit Trail',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md83',1,'']]],
  ['the_20database_4',['Verifying in the Database',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md85',1,'']]],
  ['the_20eslint_20configuration_5',['Expanding the ESLint configuration',['../dir_922c588100a187620fdc1533bc178f73.html#autotoc_md2',1,'']]],
  ['the_20transportation_20types_20api_6',['How to Test the Transportation Types API',['../md__r_e_a_d_m_e.html#autotoc_md109',1,'']]],
  ['the_20trip_7',['the Trip',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md81',1,'Step 12: Start the Trip'],['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md82',1,'Step 13: Complete the Trip'],['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md78',1,'Step 9: Approve the Trip']]],
  ['this_20application_8',['this application',['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md60',1,'What is this application?'],['../md__r_e_a_d_m_e.html#autotoc_md87',1,'What is this application?']]],
  ['to_20admin_9',['Step 2: Promote to Admin',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md71',1,'']]],
  ['to_20test_20the_20transportation_20types_20api_10',['How to Test the Transportation Types API',['../md__r_e_a_d_m_e.html#autotoc_md109',1,'']]],
  ['to_20use_11',['How to use',['../md__r_e_a_d_m_e.html#autotoc_md88',1,'']]],
  ['tracking_20planned_12',['🔄 GPS Tracking (Planned)',['../md__r_e_a_d_m_e.html#autotoc_md98',1,'']]],
  ['trail_13',['Step 14: Check the Audit Trail',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md83',1,'']]],
  ['transitions_14',['Testing Invalid Transitions',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md84',1,'']]],
  ['transportation_20management_20system_20april_202_202026_15',['Current Submission - Transportation Management System (April 2, 2026)',['../md__r_e_a_d_m_e.html#autotoc_md93',1,'']]],
  ['transportation_20type_16',['Step 4: Create a Transportation Type',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md73',1,'']]],
  ['transportation_20type_20endpoints_17',['Transportation Type Endpoints',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md34',1,'']]],
  ['transportation_20types_20api_18',['How to Test the Transportation Types API',['../md__r_e_a_d_m_e.html#autotoc_md109',1,'']]],
  ['transportation_20types_20api_20new_20fully_20implemented_19',['✅ Transportation Types API (NEW - Fully Implemented)',['../md__r_e_a_d_m_e.html#autotoc_md95',1,'']]],
  ['transportation_20types_20endpoints_20new_20',['Transportation Types Endpoints (NEW)',['../md__r_e_a_d_m_e.html#autotoc_md107',1,'']]],
  ['transportationtype_21',['TransportationType',['../class_api_1_1_models_1_1_transportation_type.html',1,'Api::Models']]],
  ['transportationtyperesponse_22',['TransportationTypeResponse',['../class_api_1_1_d_t_os_1_1_transportation_type_response.html',1,'Api::DTOs']]],
  ['transportationtypes_23',['transportationtypes',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md35',1,'GET /api/transportationtypes'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md37',1,'POST /api/transportationtypes']]],
  ['transportationtypes_20id_24',['transportationtypes id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md39',1,'DELETE /api/transportationtypes/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md36',1,'GET /api/transportationtypes/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md38',1,'PUT /api/transportationtypes/{id}']]],
  ['transportationtypescontroller_25',['TransportationTypesController',['../class_api_1_1_controllers_1_1_transportation_types_controller.html',1,'Api::Controllers']]],
  ['transportationtypeservice_26',['TransportationTypeService',['../class_api_1_1_services_1_1_transportation_type_service.html',1,'Api::Services']]],
  ['trip_27',['Trip',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md81',1,'Step 12: Start the Trip'],['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md82',1,'Step 13: Complete the Trip'],['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md77',1,'Step 8: Create a Trip'],['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md78',1,'Step 9: Approve the Trip'],['../class_api_1_1_models_1_1_trip.html',1,'Api.Models.Trip']]],
  ['trip_20endpoints_28',['Trip Endpoints',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['trip_20status_20actions_29',['Trip Status Actions',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['trip_20status_20history_30',['Trip Status History',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md57',1,'']]],
  ['trip_20system_31',['Trip System',['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md66',1,'']]],
  ['trip_20tripid_32',['GET /api/tripstatushistory/trip/{tripId}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md58',1,'']]],
  ['tripid_33',['GET /api/tripstatushistory/trip/{tripId}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md58',1,'']]],
  ['tripqueryparams_34',['TripQueryParams',['../class_api_1_1_d_t_os_1_1_trip_query_params.html',1,'Api::DTOs']]],
  ['triprequest_35',['TripRequest',['../class_api_1_1_d_t_os_1_1_trip_request.html',1,'Api::DTOs']]],
  ['tripresponse_36',['TripResponse',['../class_api_1_1_d_t_os_1_1_trip_response.html',1,'Api::DTOs']]],
  ['trips_37',['trips',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md42',1,'GET /api/trips'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'POST /api/trips']]],
  ['trips_20id_38',['trips id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md46',1,'DELETE /api/trips/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md43',1,'GET /api/trips/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md45',1,'PUT /api/trips/{id}']]],
  ['trips_20id_20approve_39',['POST /api/trips/{id}/approve',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['trips_20id_20assign_40',['POST /api/trips/{id}/assign',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['trips_20id_20cancel_41',['POST /api/trips/{id}/cancel',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['trips_20id_20complete_42',['POST /api/trips/{id}/complete',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['trips_20id_20deny_43',['POST /api/trips/{id}/deny',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['trips_20id_20noshow_44',['POST /api/trips/{id}/noshow',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['trips_20id_20start_45',['POST /api/trips/{id}/start',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md52',1,'']]],
  ['tripscontroller_46',['TripsController',['../class_api_1_1_controllers_1_1_trips_controller.html',1,'Api::Controllers']]],
  ['tripservice_47',['TripService',['../class_api_1_1_services_1_1_trip_service.html',1,'Api::Services']]],
  ['tripstatushistory_48',['TripStatusHistory',['../class_api_1_1_models_1_1_trip_status_history.html',1,'Api::Models']]],
  ['tripstatushistory_20trip_20tripid_49',['GET /api/tripstatushistory/trip/{tripId}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md58',1,'']]],
  ['tripstatushistorycontroller_50',['TripStatusHistoryController',['../class_api_1_1_controllers_1_1_trip_status_history_controller.html',1,'Api::Controllers']]],
  ['type_51',['Step 4: Create a Transportation Type',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md73',1,'']]],
  ['type_20endpoints_52',['Transportation Type Endpoints',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md34',1,'']]],
  ['types_20api_53',['How to Test the Transportation Types API',['../md__r_e_a_d_m_e.html#autotoc_md109',1,'']]],
  ['types_20api_20new_20fully_20implemented_54',['✅ Transportation Types API (NEW - Fully Implemented)',['../md__r_e_a_d_m_e.html#autotoc_md95',1,'']]],
  ['types_20endpoints_20new_55',['Transportation Types Endpoints (NEW)',['../md__r_e_a_d_m_e.html#autotoc_md107',1,'']]],
  ['typescript_20vite_56',['React + TypeScript + Vite',['../dir_922c588100a187620fdc1533bc178f73.html#autotoc_md0',1,'']]]
];
