var searchData=
[
  ['database_0',['Verifying in the Database',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md85',1,'']]],
  ['database_20models_1',['✅ Database Models',['../md__r_e_a_d_m_e.html#autotoc_md96',1,'']]],
  ['daysofweek_2',['daysOfWeek',['../class_api_1_1_models_1_1_recurrence_rule.html#addbbb633aec6351775d9a9a5890dab16',1,'Api::Models::RecurrenceRule']]],
  ['delete_20api_20driver_20id_3',['DELETE /api/driver/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md25',1,'']]],
  ['delete_20api_20rider_20id_4',['DELETE /api/rider/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md18',1,'']]],
  ['delete_20api_20transportationtypes_20id_5',['DELETE /api/transportationtypes/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md39',1,'']]],
  ['delete_20api_20trips_20id_6',['DELETE /api/trips/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md46',1,'']]],
  ['delete_20api_20vehicle_20id_7',['DELETE /api/vehicle/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md32',1,'']]],
  ['deny_8',['POST /api/trips/{id}/deny',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['denytriprequest_9',['DenyTripRequest',['../class_api_1_1_d_t_os_1_1_deny_trip_request.html',1,'Api::DTOs']]],
  ['description_10',['description',['../class_api_1_1_models_1_1_special_date.html#a32db6b89fab85706933fd89d6bf8d08b',1,'Api::Models::SpecialDate']]],
  ['development_20mode_11',['Development Mode',['../md__r_e_a_d_m_e.html#autotoc_md89',1,'']]],
  ['documentation_12',['API Documentation',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html',1,'']]],
  ['documentation_20added_13',['Documentation Added',['../md__r_e_a_d_m_e.html#autotoc_md104',1,'']]],
  ['down_14',['Down',['../class_api_1_1_migrations_1_1_initial_create.html#adefbf9c2f0ae8ea6470b6b4442e44e7a',1,'Api.Migrations.InitialCreate.Down()'],['../class_api_1_1_migrations_1_1_add_new_tables.html#aa425acdb1359c54aff40a02a2a5240f0',1,'Api.Migrations.AddNewTables.Down()']]],
  ['driver_15',['Driver',['../class_api_1_1_models_1_1_driver.html',1,'Api.Models.Driver'],['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md80',1,'Step 11: Login as Driver'],['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md75',1,'Step 6: Create a Driver']]],
  ['driver_16',['driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md21',1,'GET /api/driver'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md11',1,'POST /api/auth/register-driver'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md23',1,'POST /api/driver']]],
  ['driver_20and_20vehicle_17',['Step 10: Assign Driver and Vehicle',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md79',1,'']]],
  ['driver_20endpoints_18',['Driver Endpoints',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md20',1,'']]],
  ['driver_20id_19',['driver id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md25',1,'DELETE /api/driver/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md22',1,'GET /api/driver/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md24',1,'PUT /api/driver/{id}']]],
  ['drivercontroller_20',['DriverController',['../class_api_1_1_controllers_1_1_driver_controller.html',1,'Api::Controllers']]],
  ['driverlatestpositionresponse_21',['DriverLatestPositionResponse',['../class_api_1_1_d_t_os_1_1_driver_latest_position_response.html',1,'Api::DTOs']]],
  ['driverresponse_22',['DriverResponse',['../class_api_1_1_d_t_os_1_1_driver_response.html',1,'Api::DTOs']]],
  ['driverservice_23',['DriverService',['../class_api_1_1_services_1_1_driver_service.html',1,'Api::Services']]],
  ['dtos_20added_24',['DTOs Added',['../md__r_e_a_d_m_e.html#autotoc_md102',1,'']]]
];
