var searchData=
[
  ['a_20driver_0',['Step 6: Create a Driver',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md75',1,'']]],
  ['a_20rider_1',['Step 5: Create a Rider',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md74',1,'']]],
  ['a_20transportation_20type_2',['Step 4: Create a Transportation Type',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md73',1,'']]],
  ['a_20trip_3',['Step 8: Create a Trip',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md77',1,'']]],
  ['a_20user_4',['Step 1: Register a User',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md70',1,'']]],
  ['a_20vehicle_5',['Step 7: Create a Vehicle',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md76',1,'']]],
  ['actions_6',['Trip Status Actions',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['added_7',['Added',['../md__r_e_a_d_m_e.html#autotoc_md101',1,'API Endpoints Added'],['../md__r_e_a_d_m_e.html#autotoc_md104',1,'Documentation Added'],['../md__r_e_a_d_m_e.html#autotoc_md102',1,'DTOs Added']]],
  ['added_20updated_8',['Models Added/Updated',['../md__r_e_a_d_m_e.html#autotoc_md100',1,'']]],
  ['admin_9',['Admin',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md71',1,'Step 2: Promote to Admin'],['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md72',1,'Step 3: Login as Admin']]],
  ['admin_10',['POST /api/auth/register-admin',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md10',1,'']]],
  ['and_20vehicle_11',['Step 10: Assign Driver and Vehicle',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md79',1,'']]],
  ['api_12',['How to Test the Transportation Types API',['../md__r_e_a_d_m_e.html#autotoc_md109',1,'']]],
  ['api_20auth_20login_13',['POST /api/auth/login',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md9',1,'']]],
  ['api_20auth_20register_14',['POST /api/auth/register',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md8',1,'']]],
  ['api_20auth_20register_20admin_15',['POST /api/auth/register-admin',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md10',1,'']]],
  ['api_20auth_20register_20driver_16',['POST /api/auth/register-driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md11',1,'']]],
  ['api_20documentation_17',['API Documentation',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html',1,'']]],
  ['api_20driver_18',['api driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md21',1,'GET /api/driver'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md23',1,'POST /api/driver']]],
  ['api_20driver_20id_19',['api driver id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md25',1,'DELETE /api/driver/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md22',1,'GET /api/driver/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md24',1,'PUT /api/driver/{id}']]],
  ['api_20endpoints_20added_20',['API Endpoints Added',['../md__r_e_a_d_m_e.html#autotoc_md101',1,'']]],
  ['api_20endpoints_20summary_21',['API Endpoints Summary',['../md__r_e_a_d_m_e.html#autotoc_md105',1,'']]],
  ['api_20new_20fully_20implemented_22',['✅ Transportation Types API (NEW - Fully Implemented)',['../md__r_e_a_d_m_e.html#autotoc_md95',1,'']]],
  ['api_20rider_23',['api rider',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md14',1,'GET /api/rider'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md16',1,'POST /api/rider']]],
  ['api_20rider_20id_24',['api rider id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md18',1,'DELETE /api/rider/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md15',1,'GET /api/rider/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md17',1,'PUT /api/rider/{id}']]],
  ['api_20transportationtypes_25',['api transportationtypes',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md35',1,'GET /api/transportationtypes'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md37',1,'POST /api/transportationtypes']]],
  ['api_20transportationtypes_20id_26',['api transportationtypes id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md39',1,'DELETE /api/transportationtypes/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md36',1,'GET /api/transportationtypes/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md38',1,'PUT /api/transportationtypes/{id}']]],
  ['api_20trips_27',['api trips',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md42',1,'GET /api/trips'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'POST /api/trips']]],
  ['api_20trips_20id_28',['api trips id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md46',1,'DELETE /api/trips/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md43',1,'GET /api/trips/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md45',1,'PUT /api/trips/{id}']]],
  ['api_20trips_20id_20approve_29',['POST /api/trips/{id}/approve',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['api_20trips_20id_20assign_30',['POST /api/trips/{id}/assign',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['api_20trips_20id_20cancel_31',['POST /api/trips/{id}/cancel',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['api_20trips_20id_20complete_32',['POST /api/trips/{id}/complete',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['api_20trips_20id_20deny_33',['POST /api/trips/{id}/deny',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['api_20trips_20id_20noshow_34',['POST /api/trips/{id}/noshow',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['api_20trips_20id_20start_35',['POST /api/trips/{id}/start',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md52',1,'']]],
  ['api_20tripstatushistory_20trip_20tripid_36',['GET /api/tripstatushistory/trip/{tripId}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md58',1,'']]],
  ['api_20vehicle_37',['api vehicle',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md28',1,'GET /api/vehicle'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md30',1,'POST /api/vehicle']]],
  ['api_20vehicle_20id_38',['api vehicle id',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md32',1,'DELETE /api/vehicle/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md29',1,'GET /api/vehicle/{id}'],['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md31',1,'PUT /api/vehicle/{id}']]],
  ['application_39',['application',['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md60',1,'What is this application?'],['../md__r_e_a_d_m_e.html#autotoc_md87',1,'What is this application?']]],
  ['approve_40',['POST /api/trips/{id}/approve',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['approve_20the_20trip_41',['Step 9: Approve the Trip',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md78',1,'']]],
  ['april_202_202026_42',['April 2 2026',['../md__r_e_a_d_m_e.html#autotoc_md93',1,'Current Submission - Transportation Management System (April 2, 2026)'],['../md__r_e_a_d_m_e.html#autotoc_md99',1,'Recent Changes (April 2, 2026)']]],
  ['as_20admin_43',['Step 3: Login as Admin',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md72',1,'']]],
  ['as_20driver_44',['Step 11: Login as Driver',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md80',1,'']]],
  ['assign_45',['POST /api/trips/{id}/assign',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['assign_20driver_20and_20vehicle_46',['Step 10: Assign Driver and Vehicle',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md79',1,'']]],
  ['audit_20trail_47',['Step 14: Check the Audit Trail',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md83',1,'']]],
  ['auth_20endpoints_48',['Auth Endpoints',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md7',1,'']]],
  ['auth_20login_49',['POST /api/auth/login',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md9',1,'']]],
  ['auth_20register_50',['POST /api/auth/register',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md8',1,'']]],
  ['auth_20register_20admin_51',['POST /api/auth/register-admin',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md10',1,'']]],
  ['auth_20register_20driver_52',['POST /api/auth/register-driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md11',1,'']]],
  ['authentication_53',['Authentication',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md5',1,'Authentication'],['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md64',1,'Authentication']]],
  ['authentication_20authorization_20system_54',['✅ Authentication &amp;amp; Authorization System',['../md__r_e_a_d_m_e.html#autotoc_md94',1,'']]],
  ['authentication_20endpoints_55',['Authentication Endpoints',['../md__r_e_a_d_m_e.html#autotoc_md106',1,'']]],
  ['authorization_20system_56',['✅ Authentication &amp;amp; Authorization System',['../md__r_e_a_d_m_e.html#autotoc_md94',1,'']]]
];
