var searchData=
[
  ['pickup_0',['Pickup',['../md__r_e_a_d_m_e.html',1,'Group-9-QLI-Pickup'],['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md59',1,'Group-9-QLI-Pickup']]],
  ['planned_1',['🔄 GPS Tracking (Planned)',['../md__r_e_a_d_m_e.html#autotoc_md98',1,'']]],
  ['post_20api_20auth_20login_2',['POST /api/auth/login',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md9',1,'']]],
  ['post_20api_20auth_20register_3',['POST /api/auth/register',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md8',1,'']]],
  ['post_20api_20auth_20register_20admin_4',['POST /api/auth/register-admin',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md10',1,'']]],
  ['post_20api_20auth_20register_20driver_5',['POST /api/auth/register-driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md11',1,'']]],
  ['post_20api_20driver_6',['POST /api/driver',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md23',1,'']]],
  ['post_20api_20rider_7',['POST /api/rider',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md16',1,'']]],
  ['post_20api_20transportationtypes_8',['POST /api/transportationtypes',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md37',1,'']]],
  ['post_20api_20trips_9',['POST /api/trips',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['post_20api_20trips_20id_20approve_10',['POST /api/trips/{id}/approve',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['post_20api_20trips_20id_20assign_11',['POST /api/trips/{id}/assign',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['post_20api_20trips_20id_20cancel_12',['POST /api/trips/{id}/cancel',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['post_20api_20trips_20id_20complete_13',['POST /api/trips/{id}/complete',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['post_20api_20trips_20id_20deny_14',['POST /api/trips/{id}/deny',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['post_20api_20trips_20id_20noshow_15',['POST /api/trips/{id}/noshow',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['post_20api_20trips_20id_20start_16',['POST /api/trips/{id}/start',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md52',1,'']]],
  ['post_20api_20vehicle_17',['POST /api/vehicle',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md30',1,'']]],
  ['prerequisites_18',['Prerequisites',['../dir_bff1a75f97c7ace650ee0c8d57d0aaa5.html#autotoc_md61',1,'']]],
  ['production_20mode_19',['Production Mode',['../md__r_e_a_d_m_e.html#autotoc_md91',1,'']]],
  ['promote_20to_20admin_20',['Step 2: Promote to Admin',['../md_docs_2api_2_t_e_s_t_i_n_g___g_u_i_d_e.html#autotoc_md71',1,'']]],
  ['put_20api_20driver_20id_21',['PUT /api/driver/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md24',1,'']]],
  ['put_20api_20rider_20id_22',['PUT /api/rider/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md17',1,'']]],
  ['put_20api_20transportationtypes_20id_23',['PUT /api/transportationtypes/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md38',1,'']]],
  ['put_20api_20trips_20id_24',['PUT /api/trips/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['put_20api_20vehicle_20id_25',['PUT /api/vehicle/{id}',['../md_docs_2api_2_a_p_i___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md31',1,'']]]
];
