var hierarchy =
[
    [ "Api.DTOs.ActiveDriversPositionsResponse", "class_api_1_1_d_t_os_1_1_active_drivers_positions_response.html", null ],
    [ "Api.DTOs.AssignTripRequest", "class_api_1_1_d_t_os_1_1_assign_trip_request.html", null ],
    [ "Api.DTOs.AuthResponse", "class_api_1_1_d_t_os_1_1_auth_response.html", null ],
    [ "Api.Services.AuthService", "class_api_1_1_services_1_1_auth_service.html", null ],
    [ "Calender", "class_calender.html", null ],
    [ "Api.DTOs.CancelTripRequest", "class_api_1_1_d_t_os_1_1_cancel_trip_request.html", null ],
    [ "Api.DTOs.CompleteTripRequest", "class_api_1_1_d_t_os_1_1_complete_trip_request.html", null ],
    [ "ControllerBase", null, [
      [ "Api.Controllers.AuthController", "class_api_1_1_controllers_1_1_auth_controller.html", null ],
      [ "Api.Controllers.DriverController", "class_api_1_1_controllers_1_1_driver_controller.html", null ],
      [ "Api.Controllers.GPSController", "class_api_1_1_controllers_1_1_g_p_s_controller.html", null ],
      [ "Api.Controllers.NotificationsController", "class_api_1_1_controllers_1_1_notifications_controller.html", null ],
      [ "Api.Controllers.PingController", "class_api_1_1_controllers_1_1_ping_controller.html", null ],
      [ "Api.Controllers.ReportsController", "class_api_1_1_controllers_1_1_reports_controller.html", null ],
      [ "Api.Controllers.RiderController", "class_api_1_1_controllers_1_1_rider_controller.html", null ],
      [ "Api.Controllers.ScheduleController", "class_api_1_1_controllers_1_1_schedule_controller.html", null ],
      [ "Api.Controllers.TransportationTypesController", "class_api_1_1_controllers_1_1_transportation_types_controller.html", null ],
      [ "Api.Controllers.TripStatusHistoryController", "class_api_1_1_controllers_1_1_trip_status_history_controller.html", null ],
      [ "Api.Controllers.TripsController", "class_api_1_1_controllers_1_1_trips_controller.html", null ],
      [ "Api.Controllers.VehicleController", "class_api_1_1_controllers_1_1_vehicle_controller.html", null ]
    ] ],
    [ "Api.DTOs.CreateDriverRequest", "class_api_1_1_d_t_os_1_1_create_driver_request.html", null ],
    [ "Api.DTOs.CreateGPSBreadcrumbRequest", "class_api_1_1_d_t_os_1_1_create_g_p_s_breadcrumb_request.html", null ],
    [ "Api.DTOs.CreateRiderRequest", "class_api_1_1_d_t_os_1_1_create_rider_request.html", null ],
    [ "Api.DTOs.CreateSpecialScheduleRequest", "class_api_1_1_d_t_os_1_1_create_special_schedule_request.html", null ],
    [ "Api.DTOs.CreateTransportationTypeRequest", "class_api_1_1_d_t_os_1_1_create_transportation_type_request.html", null ],
    [ "Api.DTOs.CreateTripRequest", "class_api_1_1_d_t_os_1_1_create_trip_request.html", null ],
    [ "Api.Controllers.TripStatusHistoryController.CreateTripStatusHistoryRequest", "class_api_1_1_controllers_1_1_trip_status_history_controller_1_1_create_trip_status_history_request.html", null ],
    [ "Api.DTOs.CreateVehicleRequest", "class_api_1_1_d_t_os_1_1_create_vehicle_request.html", null ],
    [ "DbContext", null, [
      [ "Api.Data.AppDbContext", "class_api_1_1_data_1_1_app_db_context.html", null ]
    ] ],
    [ "Api.DTOs.DenyTripRequest", "class_api_1_1_d_t_os_1_1_deny_trip_request.html", null ],
    [ "Api.Models.Driver", "class_api_1_1_models_1_1_driver.html", null ],
    [ "Api.DTOs.DriverLatestPositionResponse", "class_api_1_1_d_t_os_1_1_driver_latest_position_response.html", null ],
    [ "Api.DTOs.DriverResponse", "class_api_1_1_d_t_os_1_1_driver_response.html", null ],
    [ "Api.Services.DriverService", "class_api_1_1_services_1_1_driver_service.html", null ],
    [ "Api.Models.GPS_Track_Point", "class_api_1_1_models_1_1_g_p_s___track___point.html", null ],
    [ "Api.DTOs.GPSBreadcrumbResponse", "class_api_1_1_d_t_os_1_1_g_p_s_breadcrumb_response.html", null ],
    [ "Api.Services.GPSService", "class_api_1_1_services_1_1_g_p_s_service.html", null ],
    [ "Api.Models.Hours_of_Operation", "class_api_1_1_models_1_1_hours__of___operation.html", null ],
    [ "Hub", null, [
      [ "Api.Hubs.GpsHub", "class_api_1_1_hubs_1_1_gps_hub.html", null ]
    ] ],
    [ "Api.DTOs.LoginRequest", "class_api_1_1_d_t_os_1_1_login_request.html", null ],
    [ "Api.DTOs.MarkReadRequest", "class_api_1_1_d_t_os_1_1_mark_read_request.html", null ],
    [ "Migration", null, [
      [ "Api.Migrations.AddNewTables", "class_api_1_1_migrations_1_1_add_new_tables.html", null ],
      [ "Api.Migrations.InitialCreate", "class_api_1_1_migrations_1_1_initial_create.html", null ]
    ] ],
    [ "ModelSnapshot", null, [
      [ "Api.Migrations.AppDbContextModelSnapshot", "class_api_1_1_migrations_1_1_app_db_context_model_snapshot.html", null ]
    ] ],
    [ "Api.Models.Notification", "class_api_1_1_models_1_1_notification.html", null ],
    [ "Api.DTOs.NotificationResponse", "class_api_1_1_d_t_os_1_1_notification_response.html", null ],
    [ "Api.Services.NotificationService", "class_api_1_1_services_1_1_notification_service.html", null ],
    [ "Api.DTOs.OperatingHoursResponse", "class_api_1_1_d_t_os_1_1_operating_hours_response.html", null ],
    [ "Api.DTOs.PagedNotificationResponse", "class_api_1_1_d_t_os_1_1_paged_notification_response.html", null ],
    [ "Api.DTOs.RealtimeLocationUpdate", "class_api_1_1_d_t_os_1_1_realtime_location_update.html", null ],
    [ "Api.Models.RecurrenceRule", "class_api_1_1_models_1_1_recurrence_rule.html", null ],
    [ "Api.DTOs.RegisterRequest", "class_api_1_1_d_t_os_1_1_register_request.html", null ],
    [ "Api.Models.Rider", "class_api_1_1_models_1_1_rider.html", null ],
    [ "Api.DTOs.RiderResponse", "class_api_1_1_d_t_os_1_1_rider_response.html", null ],
    [ "Api.Services.RiderService", "class_api_1_1_services_1_1_rider_service.html", null ],
    [ "Api.Services.ScheduleService", "class_api_1_1_services_1_1_schedule_service.html", null ],
    [ "Api.Models.SpecialDate", "class_api_1_1_models_1_1_special_date.html", null ],
    [ "Api.DTOs.SpecialScheduleResponse", "class_api_1_1_d_t_os_1_1_special_schedule_response.html", null ],
    [ "Api.Models.TransportationType", "class_api_1_1_models_1_1_transportation_type.html", null ],
    [ "Api.DTOs.TransportationTypeResponse", "class_api_1_1_d_t_os_1_1_transportation_type_response.html", null ],
    [ "Api.Services.TransportationTypeService", "class_api_1_1_services_1_1_transportation_type_service.html", null ],
    [ "Api.Models.Trip", "class_api_1_1_models_1_1_trip.html", null ],
    [ "Api.DTOs.TripQueryParams", "class_api_1_1_d_t_os_1_1_trip_query_params.html", null ],
    [ "Api.DTOs.TripRequest", "class_api_1_1_d_t_os_1_1_trip_request.html", null ],
    [ "Api.DTOs.TripResponse", "class_api_1_1_d_t_os_1_1_trip_response.html", null ],
    [ "Api.Services.TripService", "class_api_1_1_services_1_1_trip_service.html", null ],
    [ "Api.Models.TripStatusHistory", "class_api_1_1_models_1_1_trip_status_history.html", null ],
    [ "Api.DTOs.UpdateDriverRequest", "class_api_1_1_d_t_os_1_1_update_driver_request.html", null ],
    [ "Api.DTOs.UpdateOperatingHoursRequest", "class_api_1_1_d_t_os_1_1_update_operating_hours_request.html", null ],
    [ "Api.DTOs.UpdateRiderRequest", "class_api_1_1_d_t_os_1_1_update_rider_request.html", null ],
    [ "Api.DTOs.UpdateSpecialDatesRequest", "class_api_1_1_d_t_os_1_1_update_special_dates_request.html", [
      [ "Api.DTOs.UpdateSpecialSchedulesRequest", "class_api_1_1_d_t_os_1_1_update_special_schedules_request.html", null ]
    ] ],
    [ "Api.DTOs.UpdateTransportationTypeRequest", "class_api_1_1_d_t_os_1_1_update_transportation_type_request.html", null ],
    [ "Api.DTOs.UpdateTripRequest", "class_api_1_1_d_t_os_1_1_update_trip_request.html", null ],
    [ "Api.DTOs.UpdateVehicleRequest", "class_api_1_1_d_t_os_1_1_update_vehicle_request.html", null ],
    [ "Api.Models.User", "class_api_1_1_models_1_1_user.html", null ],
    [ "Api.Models.Vehicle", "class_api_1_1_models_1_1_vehicle.html", null ],
    [ "Api.DTOs.VehicleResponse", "class_api_1_1_d_t_os_1_1_vehicle_response.html", null ],
    [ "Api.Services.VehicleService", "class_api_1_1_services_1_1_vehicle_service.html", null ]
];